/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ukk_sppamalia;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class form_pembayaran extends javax.swing.JFrame {
    Connection con;
    DefaultTableModel tm;
    String idpembayaran;

    
    public void connect(){
        con=null;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_sppamalia","root","");
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
    }
    
    public void refreshTable(){
        tm=new DefaultTableModel(null, new Object[] {"No.", "Nama Petugas", "NISN", "Nama Siswa", "Tanggal bayar", "Bulan",  "Tarif SPP", "Jumlah Bayar"});
        jTable1.setModel(tm);
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
        tm.getDataVector().removeAllElements();
        try{
            PreparedStatement s = con.prepareStatement("SELECT pembayaran.id_pembayaran, petugas.nama_petugas, pembayaran.nisn,"
                    + " siswa.nama, pembayaran.tgl_bayar, pembayaran.bulan, spp.nominal, pembayaran.jumlah_bayar FROM pembayaran INNER JOIN "
                    + "siswa USING(nisn) INNER JOIN spp on siswa.id_spp = spp.id_spp inner join petugas on "
                    + "pembayaran.id_petugas = petugas.id_petugas");
            ResultSet r = s.executeQuery();
            while(r.next()){
                Object[] data={
                r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                r.getString(5),
                r.getString(6),
                r.getString(7),
                r.getString(8)
                };
                tm.addRow(data);
            }
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
    }
    
    private void Data(){
     try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM siswa");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {                        
                cbnisn.addItem(r.getString("nisn"));
            }
             }catch(Exception e){
            
        }
    }
    
    private void DataPetugas(){
     try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM petugas WHERE level='admin' or level='petugas'");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {                        
                cbnmpetugas.addItem(r.getString("nama_petugas"));
            }
             }catch(Exception e){
            
        }
    }
    
    private void nominal(){
     try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM spp");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {                        
                txtbyr.setText(r.getString("nominal"));
            }
             }catch(Exception e){
            
        }
    }
    /**
     * Creates new form_pembayaran
     */
    public form_pembayaran() {
        initComponents();
        connect();
        refreshTable();
        Data();
        DataPetugas();
        nominal();
        txtidPe.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbnmpetugas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbnisn = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtbyr = new javax.swing.JTextField();
        jdtanggal = new com.toedter.calendar.JDateChooser();
        txtidPe = new javax.swing.JTextField();
        txtsiswa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txttarif = new javax.swing.JTextField();
        cbbulan = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnExt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        caribulan = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entri Pembayaran");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(178, 201, 202));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe Script", 1, 27)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/payment (1).png"))); // NOI18N
        jLabel11.setText("Form Pembayaran");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        jPanel3.setBackground(new java.awt.Color(147, 181, 176));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nama Petugas :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cbnmpetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih nama" }));
        cbnmpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnmpetugasActionPerformed(evt);
            }
        });
        cbnmpetugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbnmpetugasKeyPressed(evt);
            }
        });
        jPanel3.add(cbnmpetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, -1));

        jLabel4.setText("Nama Siswa");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        cbnisn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih NISN" }));
        cbnisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnisnActionPerformed(evt);
            }
        });
        cbnisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbnisnKeyPressed(evt);
            }
        });
        jPanel3.add(cbnisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, -1));

        jLabel5.setText("Tanggal :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txt.setText("Bulan :");
        jPanel3.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel9.setText("Jumlah :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        jPanel3.add(txtbyr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 170, -1));
        jPanel3.add(jdtanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, -1));
        jPanel3.add(txtidPe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 10, -1));

        txtsiswa.setEditable(false);
        jPanel3.add(txtsiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, -1));

        jLabel6.setText("NISN :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt1.setText("Tarif SPP :");
        jPanel3.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txttarif.setEditable(false);
        jPanel3.add(txttarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, -1));

        cbbulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih bulan ", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel3.add(cbbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, 490));

        jPanel4.setBackground(new java.awt.Color(147, 181, 176));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 340));

        btnInsert.setBackground(new java.awt.Color(178, 201, 202));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/insert.png"))); // NOI18N
        btnInsert.setText("Bayar");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel4.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 100, -1));

        btnUpdate.setBackground(new java.awt.Color(178, 201, 202));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.png"))); // NOI18N
        btnUpdate.setText("Edit");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 90, -1));

        btnExt.setBackground(new java.awt.Color(178, 201, 202));
        btnExt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit.png"))); // NOI18N
        btnExt.setText("Kembali");
        btnExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtActionPerformed(evt);
            }
        });
        jPanel4.add(btnExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 100, -1));

        jButton2.setBackground(new java.awt.Color(178, 201, 202));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hapus.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel4.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 600, 430));

        jPanel5.setBackground(new java.awt.Color(147, 181, 176));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Cari pembayaran by Bulan :");

        caribulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        caribulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribulanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caribulan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel13)
                    .addComponent(caribulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 600, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Papan tulis2.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        if (txtidPe.getText().equals("") || cbnisn.getSelectedItem().equals("") || txttarif.getText().equals("") ||
            txtbyr.getText().equals(""))               
        {
            JOptionPane.showMessageDialog(this,"Data harus terisi semua");
        } else { 
            
        String tampilTanggal = "yyyy-MM-dd";
        SimpleDateFormat df = new SimpleDateFormat(tampilTanggal);
        String tanggal = String.valueOf(df.format(jdtanggal.getDate())); 
       
        
        try{
            PreparedStatement ps = con.prepareStatement("INSERT INTO pembayaran VALUES(?,?,?,?,?,?,?)");
            ps.setInt(1, 0);
            ps.setString(2, txtidPe.getText());  
            ps.setString(3, cbnisn.getSelectedItem().toString());  
            ps.setString(4, tanggal); 
            ps.setString(5, cbbulan.getSelectedItem().toString());
            ps.setString(6, txttarif.getText());  
            ps.setString(7, txtbyr.getText());         
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data telah tersimpan");
            refreshTable();
            
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtActionPerformed
        // TODO add your handling code here:
        menu m=new menu();
        m.show();
        this.dispose();
    }//GEN-LAST:event_btnExtActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i == -1){
            return;
        }
        
        String pembayaran = (String) tm.getValueAt(i, 0);
        idpembayaran=pembayaran;
        
        String petugas = (String) tm.getValueAt(i, 1);
        cbnmpetugas.setSelectedItem(petugas);
        
        String nisn = (String) tm.getValueAt(i, 2);
        cbnisn.setSelectedItem(nisn);   
        
        String siswa = (String) tm.getValueAt(i, 3);
        txtsiswa.setText(siswa);
        
        String bulan = (String) tm.getValueAt(i, 5);
        cbbulan.setSelectedItem(bulan);
        
        String nominal = (String) tm.getValueAt(i, 6);
        txttarif.setText(nominal);   
        
        String jumlah = (String) tm.getValueAt(i, 7);
        txtbyr.setText(jumlah);   
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (txtidPe.getText().equals("") || cbnisn.getSelectedItem().equals("") || txttarif.getText().equals("") ||
            txtbyr.getText().equals(""))               
        {
            JOptionPane.showMessageDialog(this,"Data harus terisi semua");
        } else {
            
        String tampilTanggal = "yyyy-MM-dd";
        SimpleDateFormat df = new SimpleDateFormat(tampilTanggal);
        String tanggal = String.valueOf(df.format(jdtanggal.getDate())); 
        
        try{
            PreparedStatement ps = con.prepareStatement("UPDATE pembayaran SET id_petugas=?, nisn=?, tgl_bayar=?, bulan=?, "
                    + "id_spp=?, jumlah_bayar=? WHERE id_pembayaran=?");
            ps.setString(1, txtidPe.getText());  
            ps.setString(2, cbnisn.getSelectedItem().toString());  
            ps.setString(3, tanggal);
            ps.setString(4, cbbulan.getSelectedItem().toString());
            ps.setString(5, txttarif.getText());
            ps.setString(6, txtbyr.getText());  
            ps.setString(7, idpembayaran);
        
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data telah tersimpan");
            refreshTable();
               
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
                }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tm=new DefaultTableModel(null, new Object[] {"No.", "Nama Petugas", "NISN", "Nama Siswa", "Tanggal Bayar", "Bulan", "Tarif SPP", "Jumlah Bayar"});
        jTable1.setModel(tm);
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
        tm.getDataVector().removeAllElements();
        try {
            PreparedStatement s = con.prepareStatement("SELECT pembayaran.id_pembayaran, petugas.nama_petugas,pembayaran.nisn,"
                    + " siswa.nama, pembayaran.tgl_bayar, pembayaran.bulan, spp.nominal, pembayaran.jumlah_bayar FROM pembayaran INNER JOIN "
                    + "siswa USING(nisn) INNER JOIN spp on siswa.id_spp = spp.id_spp inner join petugas on "
                    + "pembayaran.id_petugas = petugas.id_petugas where pembayaran.bulan LIKE '%"+caribulan.getSelectedItem().toString()+"%'");
            ResultSet r = s.executeQuery();
            while (r.next()) {
                Object[] data = {
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8)
                   
                };
                tm.addRow(data);
            }
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "n\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        refreshTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbnmpetugasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbnmpetugasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnmpetugasKeyPressed

    private void cbnisnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbnisnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnisnKeyPressed

    private void cbnmpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnmpetugasActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM petugas where nama_petugas='"+ 
                    cbnmpetugas.getSelectedItem().toString() +"'");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {                
            txtidPe.setText(r.getString("id_petugas"));    
            }
             }catch(Exception e){
            
        }
    }//GEN-LAST:event_cbnmpetugasActionPerformed

    private void cbnisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnisnActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM siswa,spp where nisn='"+ 
                    cbnisn.getSelectedItem().toString() +"'and siswa.id_spp=spp.id_spp");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {               
            txtsiswa.setText(r.getString("nama"));      
            txttarif.setText(r.getString("nominal"));  
            }
             }catch(Exception e){
            
        }
    }//GEN-LAST:event_cbnisnActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini?='"+txtsiswa.getText()
                +"'",".:: Konfirmasi ::.", JOptionPane.YES_NO_OPTION);
        if (ok==0){
        try {
            PreparedStatement ps = con.prepareStatement("DELETE FROM pembayaran WHERE id_pembayaran=?");
            ps.setString(1, idpembayaran);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data telah terhapus");
            refreshTable();
        } catch(Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
      }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void caribulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caribulanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExt;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnhapus;
    private javax.swing.JComboBox<String> caribulan;
    private javax.swing.JComboBox<String> cbbulan;
    private javax.swing.JComboBox<String> cbnisn;
    private javax.swing.JComboBox<String> cbnmpetugas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdtanggal;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt1;
    private javax.swing.JTextField txtbyr;
    private javax.swing.JTextField txtidPe;
    private javax.swing.JTextField txtsiswa;
    private javax.swing.JTextField txttarif;
    // End of variables declaration//GEN-END:variables
}
