/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ukk_sppamalia;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class menu extends javax.swing.JFrame {

        private String username;
        private String level;
        
    /**
     * Creates new form NewJFrame
     */
    public menu() {
        initComponents();
        
    }

    public void setUsername(String u) {
            username = u;
        }
        
        public void setLevel(String l) {
            level = l;
            //menu mu = new menu();
            if (level.equals("admin")) {
                
            } else if (level.equals("petugas")) {
                btndtSiswa.setEnabled(false);
                btndtPetugas.setEnabled(false);
                btndtKelas.setEnabled(false);
                btndtSpp.setEnabled(false);
                btnLaporan.setEnabled(false);
            } else if (level.equals("siswa")) {
                btndtSiswa.setEnabled(false);
                btndtPetugas.setEnabled(false);
                btndtKelas.setEnabled(false);
                btndtSpp.setEnabled(false);
                btnPembayaran.setEnabled(false);
                btnLaporan.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btndtSpp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btndtKelas = new javax.swing.JButton();
        btndtPetugas = new javax.swing.JButton();
        btndtSiswa = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(140, 650));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndtSpp.setBackground(new java.awt.Color(111, 164, 203));
        btndtSpp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndtSpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/daftar.png"))); // NOI18N
        btndtSpp.setText("Data Spp");
        btndtSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndtSppActionPerformed(evt);
            }
        });
        jPanel2.add(btndtSpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 180, 70));

        jPanel4.setBackground(new java.awt.Color(178, 201, 202));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("APLIKASI PEMBAYARAN SPP");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 880, 60));

        btndtKelas.setBackground(new java.awt.Color(111, 164, 203));
        btndtKelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndtKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/class.png"))); // NOI18N
        btndtKelas.setText("Data Kelas");
        btndtKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndtKelasActionPerformed(evt);
            }
        });
        jPanel2.add(btndtKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 170, 70));

        btndtPetugas.setBackground(new java.awt.Color(111, 164, 203));
        btndtPetugas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndtPetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/petugas.png"))); // NOI18N
        btndtPetugas.setText("Data Petugas");
        btndtPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndtPetugasActionPerformed(evt);
            }
        });
        jPanel2.add(btndtPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 190, 70));

        btndtSiswa.setBackground(new java.awt.Color(111, 164, 203));
        btndtSiswa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndtSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/student.png"))); // NOI18N
        btndtSiswa.setText("Data Siswa");
        btndtSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndtSiswaActionPerformed(evt);
            }
        });
        jPanel2.add(btndtSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 190, 70));

        btnRiwayat.setBackground(new java.awt.Color(111, 164, 203));
        btnRiwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/order history.png"))); // NOI18N
        btnRiwayat.setText("Riwayat Pembayaran");
        btnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatActionPerformed(evt);
            }
        });
        jPanel2.add(btnRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 190, 70));

        btnPembayaran.setBackground(new java.awt.Color(111, 164, 203));
        btnPembayaran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/payment (1).png"))); // NOI18N
        btnPembayaran.setText("Pembayaran Spp");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });
        jPanel2.add(btnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 190, 70));

        btnLaporan.setBackground(new java.awt.Color(111, 164, 203));
        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan.png"))); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        jPanel2.add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 170, 70));

        btnLogout.setBackground(new java.awt.Color(111, 164, 203));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 180, 70));

        jPanel5.setBackground(new java.awt.Color(178, 201, 202));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel3.setText("Menu Utama");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Papan tulis2.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 110, -1, 440));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        laporan lap= new laporan();
        lap.show();
        this.dispose();
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
        form_pembayaran fp= new form_pembayaran();
        fp.show();
        this.dispose();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        // TODO add your handling code here:
        history_pembayaran rp= new history_pembayaran();
        rp.show();
        this.dispose();
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void btndtSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndtSiswaActionPerformed
        // TODO add your handling code here:
        form_siswa fs= new form_siswa();
        fs.show();
        this.dispose();
    }//GEN-LAST:event_btndtSiswaActionPerformed

    private void btndtPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndtPetugasActionPerformed
        // TODO add your handling code here:
        form_user fu= new form_user();
        fu.show();
        this.dispose();
    }//GEN-LAST:event_btndtPetugasActionPerformed

    private void btndtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndtKelasActionPerformed
        // TODO add your handling code here:
        form_kelas fk= new form_kelas();
        fk.show();
        this.dispose();
    }//GEN-LAST:event_btndtKelasActionPerformed

    private void btndtSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndtSppActionPerformed
        // TODO add your handling code here:
        form_spp fsp= new form_spp();
        fsp.show();
        this.dispose();
    }//GEN-LAST:event_btndtSppActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.show();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btndtKelas;
    private javax.swing.JButton btndtPetugas;
    private javax.swing.JButton btndtSiswa;
    private javax.swing.JButton btndtSpp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
